-- Seed question bank: 27 questions, 3 per category x level cell (PRD §10).

insert into public.questions (statement, correct_answer, explanation, category, level) values
('Claude Code é uma ferramenta de linha de comando (CLI) da Anthropic para tarefas de engenharia de software.', true, 'Claude Code é oferecido como CLI (e também extensões de IDE/app) para ajudar em tarefas de codificação diretamente no terminal do desenvolvedor.', 'negocio', 'basico'),
('Claude Code só pode ser usado por quem já paga por uma assinatura separada do Claude.ai.', false, 'O acesso ao Claude Code depende do plano/API contratado, mas não exige necessariamente uma assinatura separada do produto de chat claude.ai.', 'negocio', 'basico'),
('Claude Code está disponível apenas como aplicativo web, sem opção de uso via terminal.', false, 'É o oposto: Claude Code nasceu como ferramenta de terminal e, a partir daí, ganhou extensões de IDE e aplicativo desktop.', 'negocio', 'basico'),

('Claude Code pode ser integrado a IDEs como VS Code e JetBrains, além do uso via terminal.', true, 'Existem extensões oficiais que trazem a experiência do Claude Code para dentro do editor, complementando o uso via terminal.', 'negocio', 'intermediario'),
('Claude Code substitui completamente a necessidade de revisão humana de código antes de ir para produção.', false, 'Claude Code acelera e assiste o trabalho de engenharia, mas revisão humana continua sendo recomendada antes de mudanças irem para produção.', 'negocio', 'intermediario'),
('Um dos casos de uso comuns do Claude Code é automatizar tarefas repetitivas, como refatoração e escrita de testes.', true, 'Refatoração, escrita de testes e outras tarefas repetitivas de engenharia estão entre os casos de uso mais comuns da ferramenta.', 'negocio', 'intermediario'),

('O Claude Agent SDK permite que desenvolvedores construam seus próprios agentes personalizados usando a mesma infraestrutura por trás do Claude Code.', true, 'O Claude Agent SDK expõe, como biblioteca, a mesma base de agente usada pelo Claude Code, para quem quer construir agentes próprios.', 'negocio', 'avancado'),
('Empresas não podem usar Claude Code em fluxos de CI/CD de forma não-interativa (modo headless).', false, 'Claude Code tem um modo não-interativo (headless/"print mode") pensado justamente para uso em scripts e pipelines automatizados.', 'negocio', 'avancado'),
('O modelo de distribuição do Claude Code inclui CLI, extensões de IDE e um aplicativo dedicado.', true, 'Além do CLI original, Claude Code também é distribuído via extensões de IDE (VS Code, JetBrains) e um aplicativo desktop.', 'negocio', 'avancado'),

('Claude Code é instalado e executado via terminal, geralmente através de um gerenciador de pacotes como npm.', true, 'A instalação padrão do Claude Code é feita via npm (ou gerenciador equivalente), e o uso principal acontece no terminal.', 'cli_basico', 'basico'),
('Depois de instalado, o Claude Code não permite personalizar nenhuma configuração do usuário.', false, 'Existem diversas configurações personalizáveis, como arquivos de settings, permissões, hooks e o próprio CLAUDE.md do projeto.', 'cli_basico', 'basico'),
('Comandos que começam com barra, como "/help", são chamados de "slash commands" no Claude Code.', true, 'Slash commands são atalhos embutidos (ou customizados) que disparam ações específicas dentro de uma sessão do Claude Code.', 'cli_basico', 'basico'),

('O arquivo CLAUDE.md na raiz de um projeto é usado para fornecer contexto/instruções persistentes ao Claude Code sobre aquele repositório.', true, 'CLAUDE.md é lido como contexto do projeto, permitindo documentar convenções, comandos e preferências específicas do repositório.', 'cli_basico', 'intermediario'),
('Por padrão, o Claude Code executa qualquer comando de terminal sem pedir confirmação ao usuário.', false, 'Por padrão há modos de permissão que pedem confirmação para ações potencialmente arriscadas, a menos que o usuário configure um modo mais permissivo.', 'cli_basico', 'intermediario'),
('O Claude Code é capaz de ler, editar e criar arquivos diretamente no projeto em que está sendo executado.', true, 'Ler, editar e criar arquivos são operações centrais do fluxo de trabalho do Claude Code dentro de um repositório.', 'cli_basico', 'intermediario'),

('É possível rodar o Claude Code em modo não-interativo (headless), útil para scripts e pipelines automatizados.', true, 'O modo não-interativo permite invocar o Claude Code programaticamente, sem uma sessão de terminal interativa, encaixando-se em automações.', 'cli_basico', 'avancado'),
('O "plan mode" do Claude Code serve para impedir qualquer edição de arquivo, mesmo depois que o usuário aprova o plano apresentado.', false, 'Plan mode existe para revisar a abordagem antes de agir; uma vez que o plano é aprovado, o agente pode seguir executando as edições necessárias.', 'cli_basico', 'avancado'),
('O Claude Code mantém um histórico de sessão que pode ser retomado posteriormente, permitindo continuar uma tarefa de onde parou.', true, 'Sessões podem ser retomadas (por exemplo, continuando ou selecionando uma conversa anterior), preservando o contexto já construído.', 'cli_basico', 'avancado'),

('"Hooks" no Claude Code permitem executar comandos automaticamente em resposta a eventos, como antes ou depois do uso de uma ferramenta.', true, 'Hooks são pontos de extensão configuráveis que disparam comandos do usuário em momentos específicos do ciclo de vida do agente.', 'avancado', 'basico'),
('A "memória" do Claude Code refere-se exclusivamente ao histórico de mensagens dentro de uma única conversa, sem persistir nada entre sessões.', false, 'Além do histórico da conversa atual, arquivos como o CLAUDE.md e outros mecanismos de memória persistem contexto entre sessões diferentes.', 'avancado', 'basico'),
('Um subagente no Claude Code sempre compartilha o mesmo contexto de conversa que o agente principal, sem nenhum isolamento.', false, 'Subagentes rodam com seu próprio contexto isolado, retornando apenas um resultado consolidado ao fluxo principal.', 'avancado', 'basico'),

('"Skills" no Claude Code são pacotes de instruções reutilizáveis que o agente pode carregar para tarefas específicas.', true, 'Skills empacotam instruções e podem ser invocadas quando a tarefa corresponde ao que a skill cobre, evitando reescrever o mesmo contexto toda vez.', 'avancado', 'intermediario'),
('O modo de permissão do Claude Code decide, entre outras coisas, se uma ação como rodar um comando ou editar um arquivo precisa de aprovação explícita do usuário.', true, 'Os modos de permissão controlam justamente o quanto o agente pode agir sem parar para pedir confirmação do usuário.', 'avancado', 'intermediario'),
('Ferramentas MCP (Model Context Protocol) só podem ser usadas dentro do Claude Code, nunca por outros clientes de IA.', false, 'MCP é um protocolo aberto, pensado para ser usado por diferentes clientes de IA, não uma funcionalidade exclusiva do Claude Code.', 'avancado', 'intermediario'),

('"Subagentes" no Claude Code permitem delegar tarefas específicas a instâncias especializadas, isolando contexto do agente principal.', true, 'Subagentes rodam com seu próprio contexto e conjunto de ferramentas, retornando um resultado consolidado ao fluxo principal.', 'avancado', 'avancado'),
('O MCP (Model Context Protocol) serve exclusivamente para conectar o Claude Code a modelos de linguagem alternativos, substituindo o modelo Claude.', false, 'MCP é um protocolo para conectar o agente a ferramentas e fontes de dados externas (ex: bancos de dados, APIs), não para trocar o modelo de linguagem em si.', 'avancado', 'avancado'),
('O Claude Agent SDK expõe uma API para orquestrar múltiplos subagentes programaticamente, fora de uma sessão interativa de CLI.', true, 'O Agent SDK permite compor agentes e subagentes em código, sem depender de uma sessão interativa de terminal para orquestrá-los.', 'avancado', 'avancado');
